// <auto-generated />
using System;
using Inmobiliaria.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Inmobiliaria.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(InmobiliariaDbContext))]
    partial class InmobiliariaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Inmobiliaria.Domain.Leasing.Contract", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateOnly?>("ActualEndDate")
                        .HasColumnType("date")
                        .HasColumnName("actual_end_date");

                    b.Property<string>("EndReason")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("end_reason");

                    b.Property<decimal?>("HonorariosPercentage")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("honorarios_percentage");

                    b.Property<decimal>("MonthlyRent")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("monthly_rent");

                    b.Property<DateOnly>("NominalEndDate")
                        .HasColumnType("date")
                        .HasColumnName("nominal_end_date");

                    b.Property<DateOnly?>("NoticeGivenDate")
                        .HasColumnType("date")
                        .HasColumnName("notice_given_date");

                    b.Property<DateOnly?>("PlannedMoveOutDate")
                        .HasColumnType("date")
                        .HasColumnName("planned_move_out_date");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_contracts");

                    b.ToTable("contracts", null, t =>
                        {
                            t.HasCheckConstraint("ck_contracts_end_reason", "end_reason IS NULL OR end_reason IN ('Expiry', 'EarlyTerminationByTenant', 'TerminationForCause', 'MutualAgreement')");

                            t.HasCheckConstraint("ck_contracts_honorarios_percentage_range", "honorarios_percentage IS NULL OR (honorarios_percentage >= 0 AND honorarios_percentage <= 100)");

                            t.HasCheckConstraint("ck_contracts_status", "status IN ('Active', 'PendingTermination', 'Ended')");
                        });
                });

            modelBuilder.Entity("Inmobiliaria.Domain.Leasing.ContractDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content_type");

                    b.Property<Guid>("ContractId")
                        .HasColumnType("uuid")
                        .HasColumnName("contract_id");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("file_name");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("kind");

                    b.Property<string>("StoragePath")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("storage_path");

                    b.Property<DateTimeOffset>("UploadedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("uploaded_at");

                    b.Property<string>("UploadedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("uploaded_by");

                    b.HasKey("Id")
                        .HasName("pk_contract_documents");

                    b.HasIndex("ContractId")
                        .HasDatabaseName("ix_contract_documents_contract_id");

                    b.ToTable("contract_documents", null, t =>
                        {
                            t.HasCheckConstraint("ck_contract_documents_kind", "kind IN ('Original', 'Addendum', 'TerminationNotice')");
                        });
                });

            modelBuilder.Entity("Inmobiliaria.Domain.Leasing.ContractParty", b =>
                {
                    b.Property<Guid>("ContractId")
                        .HasColumnType("uuid")
                        .HasColumnName("contract_id");

                    b.Property<Guid>("PartyId")
                        .HasColumnType("uuid")
                        .HasColumnName("party_id");

                    b.Property<string>("Role")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("role");

                    b.HasKey("ContractId", "PartyId", "Role")
                        .HasName("pk_contract_parties");

                    b.HasIndex("PartyId")
                        .HasDatabaseName("ix_contract_parties_party_id");

                    b.ToTable("contract_parties", null, t =>
                        {
                            t.HasCheckConstraint("ck_contract_parties_role", "role IN ('Lessor', 'Tenant', 'Codebtor')");
                        });
                });

            modelBuilder.Entity("Inmobiliaria.Domain.Leasing.ContractUnit", b =>
                {
                    b.Property<Guid>("ContractId")
                        .HasColumnType("uuid")
                        .HasColumnName("contract_id");

                    b.Property<Guid>("UnitId")
                        .HasColumnType("uuid")
                        .HasColumnName("unit_id");

                    b.Property<decimal>("SharePercentage")
                        .HasPrecision(9, 6)
                        .HasColumnType("numeric(9,6)")
                        .HasColumnName("share_percentage");

                    b.HasKey("ContractId", "UnitId")
                        .HasName("pk_contract_units");

                    b.HasIndex("UnitId")
                        .HasDatabaseName("ix_contract_units_unit_id");

                    b.ToTable("contract_units", null, t =>
                        {
                            t.HasCheckConstraint("ck_contract_units_share_percentage_range", "share_percentage > 0 AND share_percentage <= 100");
                        });
                });

            modelBuilder.Entity("Inmobiliaria.Domain.Parties.Party", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Cuil")
                        .HasColumnType("text")
                        .HasColumnName("cuil");

                    b.Property<string>("Dni")
                        .HasColumnType("text")
                        .HasColumnName("dni");

                    b.Property<string>("Domicile")
                        .HasColumnType("text")
                        .HasColumnName("domicile");

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("last_name");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text")
                        .HasColumnName("phone_number");

                    b.HasKey("Id")
                        .HasName("pk_parties");

                    b.HasIndex("Cuil")
                        .IsUnique()
                        .HasDatabaseName("ix_parties_cuil")
                        .HasFilter("cuil IS NOT NULL");

                    b.HasIndex("Dni")
                        .IsUnique()
                        .HasDatabaseName("ix_parties_dni")
                        .HasFilter("dni IS NOT NULL");

                    b.ToTable("parties", (string)null);
                });

            modelBuilder.Entity("Inmobiliaria.Domain.Units.Unit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("unit_type")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("unit_type");

                    b.HasKey("Id")
                        .HasName("pk_units");

                    b.ToTable("units", (string)null);

                    b.HasDiscriminator<string>("unit_type").HasValue("Unit");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Inmobiliaria.Domain.Units.ParkingUnit", b =>
                {
                    b.HasBaseType("Inmobiliaria.Domain.Units.Unit");

                    b.ToTable("units", (string)null);

                    b.HasDiscriminator().HasValue("parking");
                });

            modelBuilder.Entity("Inmobiliaria.Domain.Units.PropertyUnit", b =>
                {
                    b.HasBaseType("Inmobiliaria.Domain.Units.Unit");

                    b.ToTable("units", (string)null);

                    b.HasDiscriminator().HasValue("property");
                });

            modelBuilder.Entity("Inmobiliaria.Domain.Leasing.ContractDocument", b =>
                {
                    b.HasOne("Inmobiliaria.Domain.Leasing.Contract", null)
                        .WithMany()
                        .HasForeignKey("ContractId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_contract_documents_contracts_contract_id");
                });

            modelBuilder.Entity("Inmobiliaria.Domain.Leasing.ContractParty", b =>
                {
                    b.HasOne("Inmobiliaria.Domain.Leasing.Contract", null)
                        .WithMany("Parties")
                        .HasForeignKey("ContractId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_contract_parties_contracts_contract_id");

                    b.HasOne("Inmobiliaria.Domain.Parties.Party", null)
                        .WithMany()
                        .HasForeignKey("PartyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_contract_parties_parties_party_id");
                });

            modelBuilder.Entity("Inmobiliaria.Domain.Leasing.ContractUnit", b =>
                {
                    b.HasOne("Inmobiliaria.Domain.Leasing.Contract", null)
                        .WithMany("Units")
                        .HasForeignKey("ContractId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_contract_units_contracts_contract_id");

                    b.HasOne("Inmobiliaria.Domain.Units.Unit", null)
                        .WithMany()
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_contract_units_units_unit_id");
                });

            modelBuilder.Entity("Inmobiliaria.Domain.Units.Unit", b =>
                {
                    b.OwnsOne("Inmobiliaria.Domain.Shared.Address", "Address", b1 =>
                        {
                            b1.Property<Guid>("UnitId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("Apartment")
                                .HasColumnType("text")
                                .HasColumnName("address_apartment");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("address_city");

                            b1.Property<string>("Floor")
                                .HasColumnType("text")
                                .HasColumnName("address_floor");

                            b1.Property<string>("Number")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("address_number");

                            b1.Property<string>("PostalCode")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("address_postal_code");

                            b1.Property<string>("Province")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("address_province");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("address_street");

                            b1.HasKey("UnitId");

                            b1.ToTable("units");

                            b1.WithOwner()
                                .HasForeignKey("UnitId")
                                .HasConstraintName("fk_units_units_id");
                        });

                    b.Navigation("Address")
                        .IsRequired();
                });

            modelBuilder.Entity("Inmobiliaria.Domain.Leasing.Contract", b =>
                {
                    b.Navigation("Parties");

                    b.Navigation("Units");
                });
#pragma warning restore 612, 618
        }
    }
}
