// <auto-generated />
using System;
using Inmobiliaria.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Inmobiliaria.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(InmobiliariaDbContext))]
    partial class InmobiliariaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Inmobiliaria.Domain.Access.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<bool>("MustChangePassword")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("must_change_password");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("pk_app_users");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("ix_app_users_username");

                    b.ToTable("app_users", null, t =>
                        {
                            t.HasCheckConstraint("ck_app_users_username_lowercase", "username = lower(username)");
                        });
                });

            modelBuilder.Entity("Inmobiliaria.Domain.Indices.EconomicIndex", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateOnly?>("DiscontinuedFrom")
                        .HasColumnType("date")
                        .HasColumnName("discontinued_from");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid?>("SuccessorIndexId")
                        .HasColumnType("uuid")
                        .HasColumnName("successor_index_id");

                    b.HasKey("Id")
                        .HasName("pk_economic_indices");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_economic_indices_name_active")
                        .HasFilter("discontinued_from IS NULL");

                    b.ToTable("economic_indices", null, t =>
                        {
                            t.HasCheckConstraint("ck_economic_indices_successor_not_self", "successor_index_id <> id");
                        });
                });

            modelBuilder.Entity("Inmobiliaria.Domain.Indices.IndexValue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("EconomicIndexId")
                        .HasColumnType("uuid")
                        .HasColumnName("economic_index_id");

                    b.Property<decimal>("Level")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("level");

                    b.Property<DateOnly>("Period")
                        .HasColumnType("date")
                        .HasColumnName("period");

                    b.HasKey("Id")
                        .HasName("pk_index_values");

                    b.HasIndex("EconomicIndexId", "Period")
                        .IsUnique()
                        .HasDatabaseName("ix_index_values_economic_index_id_period");

                    b.ToTable("index_values", null, t =>
                        {
                            t.HasCheckConstraint("ck_index_values_level_positive", "level > 0");

                            t.HasCheckConstraint("ck_index_values_period_first_of_month", "EXTRACT(DAY FROM period) = 1");
                        });
                });

            modelBuilder.Entity("Inmobiliaria.Domain.Leasing.AdjustmentClause", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ContractId")
                        .HasColumnType("uuid")
                        .HasColumnName("contract_id");

                    b.Property<int>("IntervalMonths")
                        .HasColumnType("integer")
                        .HasColumnName("interval_months");

                    b.Property<string>("RoundingRule")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("rounding_rule");

                    b.HasKey("Id")
                        .HasName("pk_adjustment_clauses");

                    b.HasIndex("ContractId")
                        .IsUnique()
                        .HasDatabaseName("ix_adjustment_clauses_contract_id");

                    b.ToTable("adjustment_clauses", null, t =>
                        {
                            t.HasCheckConstraint("ck_adjustment_clauses_interval_months_range", "interval_months BETWEEN 1 AND 60");
                        });
                });

            modelBuilder.Entity("Inmobiliaria.Domain.Leasing.AdjustmentClauseIndex", b =>
                {
                    b.Property<Guid>("AdjustmentClauseId")
                        .HasColumnType("uuid")
                        .HasColumnName("adjustment_clause_id");

                    b.Property<Guid>("EconomicIndexId")
                        .HasColumnType("uuid")
                        .HasColumnName("economic_index_id");

                    b.Property<int>("Ordinal")
                        .HasColumnType("integer")
                        .HasColumnName("ordinal");

                    b.HasKey("AdjustmentClauseId", "EconomicIndexId")
                        .HasName("pk_adjustment_clause_indices");

                    b.HasIndex("EconomicIndexId")
                        .HasDatabaseName("ix_adjustment_clause_indices_economic_index_id");

                    b.ToTable("adjustment_clause_indices", (string)null);
                });

            modelBuilder.Entity("Inmobiliaria.Domain.Leasing.Contract", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateOnly?>("ActualEndDate")
                        .HasColumnType("date")
                        .HasColumnName("actual_end_date");

                    b.Property<string>("EndReason")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("end_reason");

                    b.Property<decimal?>("HonorariosPercentage")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("honorarios_percentage");

                    b.Property<decimal>("MonthlyRent")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("monthly_rent");

                    b.Property<DateOnly>("NominalEndDate")
                        .HasColumnType("date")
                        .HasColumnName("nominal_end_date");

                    b.Property<DateOnly?>("NoticeGivenDate")
                        .HasColumnType("date")
                        .HasColumnName("notice_given_date");

                    b.Property<DateOnly?>("PlannedMoveOutDate")
                        .HasColumnType("date")
                        .HasColumnName("planned_move_out_date");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_contracts");

                    b.ToTable("contracts", null, t =>
                        {
                            t.HasCheckConstraint("ck_contracts_end_reason", "end_reason IS NULL OR end_reason IN ('Expiry', 'EarlyTerminationByTenant', 'TerminationForCause', 'MutualAgreement')");

                            t.HasCheckConstraint("ck_contracts_honorarios_percentage_range", "honorarios_percentage IS NULL OR (honorarios_percentage >= 0 AND honorarios_percentage <= 100)");

                            t.HasCheckConstraint("ck_contracts_status", "status IN ('Active', 'PendingTermination', 'Ended')");
                        });
                });

            modelBuilder.Entity("Inmobiliaria.Domain.Leasing.ContractDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content_type");

                    b.Property<Guid>("ContractId")
                        .HasColumnType("uuid")
                        .HasColumnName("contract_id");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("file_name");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("kind");

                    b.Property<string>("StoragePath")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("storage_path");

                    b.Property<DateTimeOffset>("UploadedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("uploaded_at");

                    b.Property<Guid>("UploadedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("uploaded_by_user_id");

                    b.HasKey("Id")
                        .HasName("pk_contract_documents");

                    b.HasIndex("ContractId")
                        .HasDatabaseName("ix_contract_documents_contract_id");

                    b.HasIndex("UploadedByUserId")
                        .HasDatabaseName("ix_contract_documents_uploaded_by_user_id");

                    b.ToTable("contract_documents", null, t =>
                        {
                            t.HasCheckConstraint("ck_contract_documents_kind", "kind IN ('Original', 'Addendum', 'TerminationNotice')");
                        });
                });

            modelBuilder.Entity("Inmobiliaria.Domain.Leasing.ContractParty", b =>
                {
                    b.Property<Guid>("ContractId")
                        .HasColumnType("uuid")
                        .HasColumnName("contract_id");

                    b.Property<Guid>("PartyId")
                        .HasColumnType("uuid")
                        .HasColumnName("party_id");

                    b.Property<string>("Role")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("role");

                    b.HasKey("ContractId", "PartyId", "Role")
                        .HasName("pk_contract_parties");

                    b.HasIndex("PartyId")
                        .HasDatabaseName("ix_contract_parties_party_id");

                    b.ToTable("contract_parties", null, t =>
                        {
                            t.HasCheckConstraint("ck_contract_parties_role", "role IN ('Lessor', 'Tenant', 'Codebtor')");
                        });
                });

            modelBuilder.Entity("Inmobiliaria.Domain.Leasing.ContractUnit", b =>
                {
                    b.Property<Guid>("ContractId")
                        .HasColumnType("uuid")
                        .HasColumnName("contract_id");

                    b.Property<Guid>("UnitId")
                        .HasColumnType("uuid")
                        .HasColumnName("unit_id");

                    b.Property<decimal>("SharePercentage")
                        .HasPrecision(9, 6)
                        .HasColumnType("numeric(9,6)")
                        .HasColumnName("share_percentage");

                    b.HasKey("ContractId", "UnitId")
                        .HasName("pk_contract_units");

                    b.HasIndex("UnitId")
                        .HasDatabaseName("ix_contract_units_unit_id");

                    b.ToTable("contract_units", null, t =>
                        {
                            t.HasCheckConstraint("ck_contract_units_share_percentage_range", "share_percentage > 0 AND share_percentage <= 100");
                        });
                });

            modelBuilder.Entity("Inmobiliaria.Domain.Leasing.RentAdjustment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Coefficient")
                        .HasPrecision(12, 6)
                        .HasColumnType("numeric(12,6)")
                        .HasColumnName("coefficient");

                    b.Property<DateTimeOffset>("ConfirmedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("confirmed_at");

                    b.Property<Guid?>("ConfirmedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("confirmed_by");

                    b.Property<Guid>("ContractId")
                        .HasColumnType("uuid")
                        .HasColumnName("contract_id");

                    b.Property<Guid?>("CorrectsAdjustmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("corrects_adjustment_id");

                    b.Property<DateOnly>("EffectiveDate")
                        .HasColumnType("date")
                        .HasColumnName("effective_date");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("kind");

                    b.Property<decimal>("NewCanon")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("new_canon");

                    b.Property<decimal>("PreviousCanon")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("previous_canon");

                    b.HasKey("Id")
                        .HasName("pk_rent_adjustments");

                    b.HasIndex("ConfirmedBy")
                        .HasDatabaseName("ix_rent_adjustments_confirmed_by");

                    b.HasIndex("ContractId")
                        .HasDatabaseName("ix_rent_adjustments_contract_id");

                    b.ToTable("rent_adjustments", null, t =>
                        {
                            t.HasCheckConstraint("ck_rent_adjustments_effective_date_first_of_month", "EXTRACT(DAY FROM effective_date) = 1");

                            t.HasCheckConstraint("ck_rent_adjustments_kind_corrects", "(kind = 'Correction') = (corrects_adjustment_id IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("Inmobiliaria.Domain.Leasing.RentAdjustmentIndexValue", b =>
                {
                    b.Property<Guid>("RentAdjustmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("rent_adjustment_id");

                    b.Property<Guid>("ReferencedIndexId")
                        .HasColumnType("uuid")
                        .HasColumnName("referenced_index_id");

                    b.Property<decimal>("BaseLevel")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("base_level");

                    b.Property<DateOnly>("BasePeriod")
                        .HasColumnType("date")
                        .HasColumnName("base_period");

                    b.Property<decimal>("EndLevel")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("end_level");

                    b.Property<DateOnly>("EndPeriod")
                        .HasColumnType("date")
                        .HasColumnName("end_period");

                    b.Property<Guid>("ResolvedIndexId")
                        .HasColumnType("uuid")
                        .HasColumnName("resolved_index_id");

                    b.Property<decimal>("Variation")
                        .HasPrecision(12, 6)
                        .HasColumnType("numeric(12,6)")
                        .HasColumnName("variation");

                    b.HasKey("RentAdjustmentId", "ReferencedIndexId")
                        .HasName("pk_rent_adjustment_index_values");

                    b.ToTable("rent_adjustment_index_values", (string)null);
                });

            modelBuilder.Entity("Inmobiliaria.Domain.Parties.Party", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Cuil")
                        .HasColumnType("text")
                        .HasColumnName("cuil");

                    b.Property<string>("Dni")
                        .HasColumnType("text")
                        .HasColumnName("dni");

                    b.Property<string>("Domicile")
                        .HasColumnType("text")
                        .HasColumnName("domicile");

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("last_name");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text")
                        .HasColumnName("phone_number");

                    b.HasKey("Id")
                        .HasName("pk_parties");

                    b.HasIndex("Cuil")
                        .IsUnique()
                        .HasDatabaseName("ix_parties_cuil")
                        .HasFilter("cuil IS NOT NULL");

                    b.HasIndex("Dni")
                        .IsUnique()
                        .HasDatabaseName("ix_parties_dni")
                        .HasFilter("dni IS NOT NULL");

                    b.ToTable("parties", (string)null);
                });

            modelBuilder.Entity("Inmobiliaria.Domain.Units.Unit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("unit_type")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("unit_type");

                    b.HasKey("Id")
                        .HasName("pk_units");

                    b.ToTable("units", (string)null);

                    b.HasDiscriminator<string>("unit_type").HasValue("Unit");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Inmobiliaria.Domain.Units.ParkingUnit", b =>
                {
                    b.HasBaseType("Inmobiliaria.Domain.Units.Unit");

                    b.ToTable("units", (string)null);

                    b.HasDiscriminator().HasValue("parking");
                });

            modelBuilder.Entity("Inmobiliaria.Domain.Units.PropertyUnit", b =>
                {
                    b.HasBaseType("Inmobiliaria.Domain.Units.Unit");

                    b.ToTable("units", (string)null);

                    b.HasDiscriminator().HasValue("property");
                });

            modelBuilder.Entity("Inmobiliaria.Domain.Indices.IndexValue", b =>
                {
                    b.HasOne("Inmobiliaria.Domain.Indices.EconomicIndex", null)
                        .WithMany()
                        .HasForeignKey("EconomicIndexId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_index_values_economic_indices_economic_index_id");
                });

            modelBuilder.Entity("Inmobiliaria.Domain.Leasing.AdjustmentClause", b =>
                {
                    b.HasOne("Inmobiliaria.Domain.Leasing.Contract", null)
                        .WithOne("AdjustmentClause")
                        .HasForeignKey("Inmobiliaria.Domain.Leasing.AdjustmentClause", "ContractId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_adjustment_clauses_contracts_contract_id");
                });

            modelBuilder.Entity("Inmobiliaria.Domain.Leasing.AdjustmentClauseIndex", b =>
                {
                    b.HasOne("Inmobiliaria.Domain.Leasing.AdjustmentClause", null)
                        .WithMany("Indices")
                        .HasForeignKey("AdjustmentClauseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_adjustment_clause_indices_adjustment_clauses_adjustment_cla");

                    b.HasOne("Inmobiliaria.Domain.Indices.EconomicIndex", null)
                        .WithMany()
                        .HasForeignKey("EconomicIndexId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_adjustment_clause_indices_economic_indices_economic_index_id");
                });

            modelBuilder.Entity("Inmobiliaria.Domain.Leasing.ContractDocument", b =>
                {
                    b.HasOne("Inmobiliaria.Domain.Leasing.Contract", null)
                        .WithMany()
                        .HasForeignKey("ContractId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_contract_documents_contracts_contract_id");

                    b.HasOne("Inmobiliaria.Domain.Access.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UploadedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_contract_documents_app_users_uploaded_by_user_id");
                });

            modelBuilder.Entity("Inmobiliaria.Domain.Leasing.ContractParty", b =>
                {
                    b.HasOne("Inmobiliaria.Domain.Leasing.Contract", null)
                        .WithMany("Parties")
                        .HasForeignKey("ContractId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_contract_parties_contracts_contract_id");

                    b.HasOne("Inmobiliaria.Domain.Parties.Party", null)
                        .WithMany()
                        .HasForeignKey("PartyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_contract_parties_parties_party_id");
                });

            modelBuilder.Entity("Inmobiliaria.Domain.Leasing.ContractUnit", b =>
                {
                    b.HasOne("Inmobiliaria.Domain.Leasing.Contract", null)
                        .WithMany("Units")
                        .HasForeignKey("ContractId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_contract_units_contracts_contract_id");

                    b.HasOne("Inmobiliaria.Domain.Units.Unit", null)
                        .WithMany()
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_contract_units_units_unit_id");
                });

            modelBuilder.Entity("Inmobiliaria.Domain.Leasing.RentAdjustment", b =>
                {
                    b.HasOne("Inmobiliaria.Domain.Access.AppUser", null)
                        .WithMany()
                        .HasForeignKey("ConfirmedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_rent_adjustments_app_users_confirmed_by");

                    b.HasOne("Inmobiliaria.Domain.Leasing.Contract", null)
                        .WithMany("Adjustments")
                        .HasForeignKey("ContractId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_rent_adjustments_contracts_contract_id");
                });

            modelBuilder.Entity("Inmobiliaria.Domain.Leasing.RentAdjustmentIndexValue", b =>
                {
                    b.HasOne("Inmobiliaria.Domain.Leasing.RentAdjustment", null)
                        .WithMany("IndexValues")
                        .HasForeignKey("RentAdjustmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_rent_adjustment_index_values_rent_adjustments_rent_adjustme");
                });

            modelBuilder.Entity("Inmobiliaria.Domain.Units.Unit", b =>
                {
                    b.OwnsOne("Inmobiliaria.Domain.Shared.Address", "Address", b1 =>
                        {
                            b1.Property<Guid>("UnitId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("Apartment")
                                .HasColumnType("text")
                                .HasColumnName("address_apartment");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("address_city");

                            b1.Property<string>("Floor")
                                .HasColumnType("text")
                                .HasColumnName("address_floor");

                            b1.Property<string>("Number")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("address_number");

                            b1.Property<string>("PostalCode")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("address_postal_code");

                            b1.Property<string>("Province")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("address_province");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("address_street");

                            b1.HasKey("UnitId");

                            b1.ToTable("units");

                            b1.WithOwner()
                                .HasForeignKey("UnitId")
                                .HasConstraintName("fk_units_units_id");
                        });

                    b.Navigation("Address")
                        .IsRequired();
                });

            modelBuilder.Entity("Inmobiliaria.Domain.Leasing.AdjustmentClause", b =>
                {
                    b.Navigation("Indices");
                });

            modelBuilder.Entity("Inmobiliaria.Domain.Leasing.Contract", b =>
                {
                    b.Navigation("AdjustmentClause");

                    b.Navigation("Adjustments");

                    b.Navigation("Parties");

                    b.Navigation("Units");
                });

            modelBuilder.Entity("Inmobiliaria.Domain.Leasing.RentAdjustment", b =>
                {
                    b.Navigation("IndexValues");
                });
#pragma warning restore 612, 618
        }
    }
}
